version: '3.8'

services:
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "5252"
    volumes:
      - ./back-end:/app
    container_name: back-end-1

  back-end-2:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "5252"
    volumes:
      - ./back-end:/app
    container_name: back-end-2

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./front-end:/var/www/html
    container_name: front-end

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: softy-pinko-proxy:task6
    ports:
      - "80:80"
    depends_on:
      - front-end
      - back-end
      - back-end-2
    container_name: proxy
    networks:
      - default
